### ISSUE TITLE
Task: UI Revamp

### ISSUE THREAD

**Issue by Maaz-Code** [LeidiFlores/cuchi-pomodoro#10]
Hello @LeidiFlores , I would like to work on the basic UI of this project to make it more appealing.

- My main target would be to provide adequate styling to the components and keep a steady theme throughout. 
- If I find it suitable, I can use a UI framework for the project.

Kindly assign me this issue so that I can start working on it under Hacktoberfest.

**Comment by LeidiFlores** [comment]
hello @Maaz-Code !

ok, go ahead :)

**Comment by Maaz-Code** [comment]
Hello @LeidiFlores, Since a lot of UI work has already been done, I will not be going ahead with my changes to avoid conflicts. I am closing this issue as a duplicate.
