### ISSUE TITLE
FEAT: Add Light Mode Theme

### ISSUE THREAD

**Issue by sendhyrama** [LeidiFlores/cuchi-pomodoro#12]
Currently, the Pomodoro web only supports a dark mode interface. While dark mode is beneficial for reducing eye strain in low-light environments, providing a light mode option would enhance accessibility and user experience for those who prefer a brighter interface during daytime or in well-lit settings.

### Proposed Solution:
- Add a toggle button that users can switch between light and dark mode.
- Ensure consistent styling across all components when switching between themes.

**Comment by TanishaMehta17** [comment]
@LeidiFlores Can you please assign me this task

**Comment by LeidiFlores** [comment]
hello, thanks @sendhyrama, do you want to do it?

**Comment by sendhyrama** [comment]
> hello, thanks @sendhyrama, do you want to do it?

hi, you can assign to others

**Comment by natnichalerdwa** [comment]
Could I work on this please?
