### ISSUE TITLE
FEAT: Add Short Break (5 mins) and Long Break (15 mins) Options

### ISSUE THREAD

**Issue by sendhyrama** [LeidiFlores/cuchi-pomodoro#13]
The current Pomodoro web application only supports the standard Pomodoro timer without any break options. To enhance the functionality and align with the traditional Pomodoro technique, it would be beneficial to add two types of breaks: a 5-minute short break and a 15-minute long break.

### Proposed Solution:
- Add a 5-minute short break option that can be activated after a single Pomodoro session.
- Add a 15-minute long break option, triggered after completing four Pomodoro sessions.
- Allow users to switch between the Pomodoro session, short break, and long break.

**Comment by SanidhyaSharma28** [comment]
I am interested in this can you assign it to me i can get it done.

**Comment by LeidiFlores** [comment]
hello, thanks @sendhyrama, do you want to do it?

**Comment by SanidhyaSharma28** [comment]
@LeidiFlores can I get it?

**Comment by sendhyrama** [comment]
> hello, thanks @sendhyrama, do you want to do it?

Hi, you can assign to others

**Comment by SanidhyaSharma28** [comment]
can i try it out?? @LeidiFlores

**Comment by LeidiFlores** [comment]
Hello @SanidhyaSharma28 yes, go ahead :)
