### ISSUE TITLE
FEAT: Add Timer Notification with Sound Alert

### ISSUE THREAD

**Issue by sendhyrama** [LeidiFlores/cuchi-pomodoro#14]
The current Pomodoro web application lacks an audible alert when the timer reaches the end of a session. To enhance user experience and ensure users are aware when the timer finishes, a sound notification (such as a bell) should be added to signal the end of both Pomodoro sessions and breaks.

### Proposed Solution:
- Add a sound alert (bell tone) that plays when the timer ends for both Pomodoro sessions and breaks.
- Provide an option for users to enable or disable the sound notification in the settings.
- Ensure the notification volume is adjustable or respects the system volume.

**Comment by LeidiFlores** [comment]
hello @sendhyrama 

perfect, go ahead :)
