### ISSUE TITLE
Add a interesting moving background 

### ISSUE THREAD

**Issue by mr-panther01** [LeidiFlores/cuchi-pomodoro#17]

**Comment by mr-panther01** [comment]
https://github.com/user-attachments/assets/758ba4e6-5ee9-4eb5-9bcf-e3d4371abb2d

sample background for this

**Comment by LeidiFlores** [comment]
hello @mr-panther01 

that it's interesting, go ahead :)

**Comment by BaniSinghgithub** [comment]
hello sir @LeidiFlores , pls assign this work to me
