### ISSUE TITLE
CONTRIBUTING.md file is missing

### ISSUE THREAD

**Issue by Jhananithaa** [LeidiFlores/cuchi-pomodoro#19]
Need to make a code of conduct file. To enhance the collaboration experience for contributors and maintainers during Hacktoberfest, it is essential to include a CONTRIBUTING.md file in the repository. This file will serve as a guide for potential contributors, providing clear instructions on how to get involved, the coding standards to follow, and any specific practices relevant to our project.

**Comment by Jhananithaa** [comment]
Hi @LeidiFlores - Could you please assign this to me, I will work on this

**Comment by LeidiFlores** [comment]
hello @Jhananithaa 

ok, go ahead :)
