### ISSUE TITLE
PULL_REQUEST_TEMPLATE.md is missing 

### ISSUE THREAD

**Issue by anshgautam-github** [LeidiFlores/cuchi-pomodoro#22]
Description:

I have noticed that the repository currently lacks a PULL_REQUEST_TEMPLATE.md file. A pull request template is essential for guiding contributors in submitting their pull requests consistently and effectively. It helps ensure that all necessary information is provided, which can improve the review process and maintain code quality.

**Comment by LeidiFlores** [comment]
hello @anshgautam-github 

ok, go ahead :)!
