### ISSUE TITLE
Add Background Image for Enhanced Aesthetic

### ISSUE THREAD

**Issue by anshgautam-github** [LeidiFlores/cuchi-pomodoro#23]
I would like to propose adding a background image to the Cuchi Pomodoro application to give it a more appealing look and vibe. A visually pleasing background can significantly enhance the user experience and create a more inviting atmosphere for users while they manage their time effectively.

**Comment by LeidiFlores** [comment]
hello @anshgautam-github 

go ahead, but please use an image with soft style something calm :)

**Comment by BaniSinghgithub** [comment]
hello sir @LeidiFlores  , pls assign this work to me

**Comment by anshgautam-github** [comment]
> hello @anshgautam-github
> 
> go ahead, but please use an image with soft style something calm :)

Sure
