### ISSUE TITLE
Feature Request: Add Hover Effects to All Elements for Enhanced Interactivity

### ISSUE THREAD

**Issue by saismrutiranjan18** [LeidiFlores/cuchi-pomodoro#33]
To improve the user experience and interactivity of the page, I propose adding hover effects to all clickable elements. This feature would provide visual feedback to users when they interact with various components, making the interface more engaging and intuitive. Consistent hover effects across the site will not only enhance the aesthetics but also help users easily identify interactive elements.

![image](https://github.com/user-attachments/assets/e81c4c33-c917-4582-9182-351857e00127)

please assign me under Hacktoberfest

**Comment by eduardomrodrigues** [comment]
Hi, @saismrutiranjan18!! How are you? Can you give me an issue for this great project? Tnks!!

**Comment by harith-hacky03** [comment]
I'm ready to fix it? Can you assign me ?
