### ISSUE TITLE
In dark mode the Dark theme should be applicable to Full screen 

### ISSUE THREAD

**Issue by Harshcbx8** [LeidiFlores/cuchi-pomodoro#40]
In your website in dark mode there is only the center portion convert to in dark theme, while
![Screenshot 2024-10-22 095902](https://github.com/user-attachments/assets/aa9b583f-b78c-4471-a957-d70291c3fddf)
 it should be to convert full screen in dark theme. 

And the footer should be at more in bottom i will fix these issues please assign it to me!

**Comment by Harshcbx8** [comment]
Even in light mode the text are black and the white section is transparent where the timer present
![Screenshot 2024-10-22 100402](https://github.com/user-attachments/assets/a94264b5-162a-48e0-9699-be82c5931d28)

**Comment by LeidiFlores** [comment]
hello @Harshcbx8 

please update your repo because the currently view for light theme is:

<img width="1045" alt="Screenshot 2024-10-21 at 10 39 47 p m" src="https://github.com/user-attachments/assets/3ba6f0fc-6d1c-4091-bc3c-8f86b024c239">

**Comment by natnicha-lerdwanawattana** [comment]
@Harshcbx8 
The center portion is on purpose. I did not want to cover the whole background. I wanted a floated timer visual.

**Comment by Harshcbx8** [comment]
@natnicha-lerdwanawattana yet the website looks good, my raise issue is invalid!
