### ISSUE TITLE
Issue Running Dev

### ISSUE THREAD

**Issue by natnichalerdwa** [LeidiFlores/cuchi-pomodoro#49]
Hi,

I'm not sure if anyone has the same issue, but I just synced my fork with the latest update but now when I try to run dev, the timer doesn't show up anymore. Does anyone have any idea how to fix it? Could it be my browser? 

Thank you!
Natnicha

![Screenshot 2024-10-25 at 8 26 46 PM](https://github.com/user-attachments/assets/8d544dd7-6b48-4233-8632-a4964933d653)

**Comment by LeidiFlores** [comment]
I'm already fix that, thank u @natnichalerdwa  for open the issue!
