### ISSUE TITLE
update readme documentation

### ISSUE THREAD

**Issue by irshadsiddi** [LeidiFlores/cuchi-pomodoro#7]
improvise the readme documentation like what the project is all about?

**Comment by irshadsiddi** [comment]
@LeidiFlores yes, i want to do it.. if possible please add the hacktoberfest label.

**Comment by irshadsiddi** [comment]
@LeidiFlores or else just assign it to me ill improvise it no need to add hacktoberfest label.

**Comment by LeidiFlores** [comment]
go ahead @irshadsiddi !
